apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  GIN_MODE: "debug"
  APP_MODE: "production"
  GIN_PORT: "8080"
  JWT_EXPIRED_TIME_MIN: "10000"
  
  PSQL_HOST: localhost
  PSQL_PORT: 5432