apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
stringData:
  REGISTRY_URL: "ghcr.io"
  REDIS_DB: "0"
  REDIS_EXPIRE: "86400"
  REDIS_ADDR: "redis-service:6379"
# base64 encoded. encode with "echo -n some-text | base64"
data:
 # It's GitHub PAT
  REGISTRY_PASS: password
  REGISTRY_EMAIL: email
  REGISTRY_USERNAME: username
  JWT_PUBLIC_KEY: |
   LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQzJQUGJHSmtWa3FtRjUKT3Q1ZnlMdEcxTk9nUFdoTy80aDhU
  JWT_PRIVATE_KEY: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQzJQUGJHSmtWa3FtRjUKT3Q1ZnlMdEcxTk9nUFdoTy80aDhU

  # DB name
  PSQL_DB: db
  # Db user
  PSQL_USER: user
  # Db password 
  PSQL_PASSWORD: 1234
  REDIS_PASSWORD: Cg==