apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
stringData:
  REGISTRY_URL: "ghcr.io"
# base64 encoded. encode with "echo some-text | base64"
data:
 # It's GitHub PAT
  REGISTRY_PASS: Z2hwXzc2bGhjaDJtbkNoNEJUeVVGWnZic3JvVmt6a3U3MjJsT1dKVAo=
  REGISTRY_EMAIL: cS5zaGFyYWZpYW5AZ21haWwuY29tCg==
  REGISTRY_USERNAME: cS1zaGFyYWZpYW4K
