apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
stringData:
  REGISTRY_URL: "ghcr.io"
# base64 encoded. encode with "echo some-text | base64"
data:
 # It's GitHub PAT
  REGISTRY_PASS: password
  REGISTRY_EMAIL: email
  REGISTRY_USERNAME: username
  JWT_PUBLIC_KEY: |
   LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQzJQUGJHSmtWa3FtRjUKT3Q1ZnlMdEcxTk9nUFdoTy80aDhU
  JWT_PRIVATE_KEY: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQzJQUGJHSmtWa3FtRjUKT3Q1ZnlMdEcxTk9nUFdoTy80aDhU