apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
              ephemeral-storage: 0.5Gi
            limits:
              cpu: 250m
              memory: 500Mi
              ephemeral-storage: 0.5Gi