apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: redis-service
  labels:
    app: redis
spec:
  # Choose how to expose your service
  type: ClusterIP
  ports:
    - name: http
      # The port number to expose the service
      port: 6379
      protocol: TCP
      targetPort: 6379
  # Pod to route service traffic  
  selector:
    app: redis # Matches the app label in your PostgreSQL deployment