apiVersion: v1
# define a resource for volume chain
kind: PersistentVolumeClaim
metadata:
  # Name the volume chain
  name: db-persistent-volume-claim
spec:
  storageClassName: standard # manual
  accessModes:
    # only AccessModes [ReadWriteOnce] are supported 
    - ReadWriteOnce
  # PVC requesting resources
  resources:
    requests:
      # the PVC storage
      storage: 3Gi
  # hostPath:
  #   path: "/var/lib/postgresql/data"