name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/dms:latest
    - name: Push the Docker image to GitHub Container Registry
      run: |
        REPO=${{ github.repository }}
        USERNAME=$(echo $REPO | cut -d'/' -f1)
        REPONAME=$(echo $REPO | cut -d'/' -f2)
        echo "Username: $USERNAME"
        echo "Repository Name: $REPONAME"
